[project]
name = "quant-engine"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "black>=26.1.0",
    "pydantic>=2.12.5",
    "pytest>=9.0.2",
    "ruff>=0.14.14",
]
